"""Pure logic for the LLM Panels node — no ComfyUI imports, no network I/O.

Kept separate from `node_llm_panels.py` so it can be unit-tested in isolation
(see `test_llm_panels.py` at the repo root) and so the node file itself stays
thin, per the Pixaroma-style node + `_helpers.py` split. The actual HTTP POST
(stdlib `urllib` only) lives in the node file — these helpers only build the
request payload and parse the response, both pure functions.

`DEFAULT_SYSTEM_PROMPT` is the finalized, verbatim prompt text: a plain
string constant (NOT `.format()`-ed by `build_messages` or anywhere else),
so its literal `{n}` placeholders and `[slot]` template markers are sent to
the LLM as-is — they're instructional template syntax for the model to fill
in, not Python format fields. It teaches the target LLM the package's
LABELED-PROSE scene format (see `_scene_creator_helpers.build_scene_text` /
`render_character_paragraph` for the canonical Python implementation of a
similar shape): a leading bare, unterminated tags line, one `;`-terminated
`Name: <appearance>, <clothes>;` paragraph per character (persistent
identity only — no pose/action here), a `;`-terminated `Background: ...;`
setting-bible line, then an UNLABELED, un-terminated two-line tail — a
natural-language composition sentence (naming each character's pose/
action/expression/gaze and framing), then a shot-distance/depth-of-field/
lighting line — followed by a `--- STORY ---` narration/dialogue block —
so panels generated by the LLM slot directly into `PanelBatch` -> downstream
CLIP/KSampler nodes (image prompt) plus a separate story/dialogue output,
without any reformatting.
"""

from __future__ import annotations

import re

DEFAULT_BASE_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_MODEL = "openrouter/auto"

PANEL_DELIMITER_TEMPLATE = "=== PANEL {n} ==="
SYNOPSIS_DELIMITER = "=== SYNOPSIS ==="

DEFAULT_SYSTEM_PROMPT = """You are a webtoon panel writer. Given a story/scene brief (and, on continuation, the panels so far + a synopsis), you write the panels that come next, each describing ONE image plus its narration/dialogue, in a strict LABELED-PROSE format for a text-to-image prompt encoder (Anima). Plain labeled-prose only — never JSON, markdown, or code fences.

Each panel MUST follow this EXACT SHAPE (fill the [slots]; keep the ";" and layout exactly):

=== PANEL {n} ===
[quality tags], [recency], [safety], [character count], [relations]

[Name]: [gender], [maturity], [body build], [breast size], [skin], [hair length], [hair style], [bangs/sidelocks], [hair color], [eye color], [eye shape], [marks], [clothes top→bottom: headwear, top/dress, bottom, outerwear, legwear, footwear, accessories];

[Name 2]: [same identity structure — appearance then clothes];

Background: [indoors/outdoors], [location], [time of day], [key furniture/objects], [atmosphere], [far background elements];

[framing/viewpoint], [Named A: pose + expression + gaze], [Named B: pose/action + gaze], [interaction + key props re-stated], [depth: who is foreground/blurred vs who is sharp & facing camera]
[shot distance], [depth of field / focus], [lighting quality + color]

--- STORY ---
Narration: [caption or internal monologue]
[Name]: "[dialogue]"
[Name 2]: "[dialogue]"

EXAMPLE:

=== PANEL 1 ===
masterpiece, best quality, score_7, newest, safe, 1girl, 1boy, hetero

Sera: woman, mature female, slender, medium breasts, pale skin, long hair, hime cut, blunt bangs, sidelocks, black hair, red eyes, tsurime, mole under eye, white blouse, black blazer, pencil skirt, black pantyhose, high heels;

Jae: man, tall, muscular, short hair, messy hair, undercut, dark brown hair, brown eyes, stubble, light blue dress shirt, loosened navy tie, charcoal slacks, dress shoes;

Background: indoors, modern open-plan office, night, rows of desks, computer monitors, glowing screens, large window, city lights outside, potted plant;

over-the-shoulder from behind Jae, Sera sits turned in her office chair looking up at him with a surprised warm smile as she reaches for the paper coffee cup he holds out, Jae leaning over her from behind, his back and shoulder blurred in the foreground while Sera stays in sharp focus facing the camera
medium shot, shallow depth of field, bokeh, fluorescent lighting, cool blue monitor glow

--- STORY ---
Narration: Long after everyone had gone home, the office still hummed.
Jae: "You're still here?"
Sera: "...I could ask you the same thing."

FORMAT RULES

1) TAGS LINE (first line, bare, no label, no ";"): quality + recency + safety + character count. Quality/recency/safety stay the SAME every panel (e.g. "masterpiece, best quality, score_7, newest, safe"); the count changes per panel to match who is present (1girl, 1boy, 2girls, hetero, multiple girls). An optional @artist tag may be added.

2) CHARACTER PARAGRAPHS — one per character, "Name: <appearance>, <clothes>;". PERSISTENT IDENTITY ONLY, repeated verbatim in every panel (the character bible). NO pose, action, expression, gaze, or framing here.
   - appearance order: gender → maturity (adults: "mature female") → body build (one of slender/petite/curvy/muscular/toned) → breast size → skin → hair length → hair style → bangs/sidelocks → hair color → eye color → eye shape (tsurime/tareme) → distinguishing marks (mole under eye, scar, heterochromia).
   - clothes order (top→bottom): headwear → top/dress → bottom → outerwear → legwear → footwear → accessories.
   - lowercase, canonical Gelbooru tags, spaces not underscores (except score_N). No invented tags; no left/right on marks (use "mole under eye"). Each character paragraph ends with ";". Keep a character's appearance + clothes IDENTICAL across panels unless the story explicitly changes an outfit.

3) BACKGROUND (labeled, ends with ";"): the setting bible — "Background: indoors/outdoors, location, time of day, key furniture/objects, atmosphere, far elements;". Reuse the SAME tags whenever the story returns to a location; only change what actually changed. Time-of-day here, NOT light color.

4) COMPOSITION SENTENCE (unlabeled, no ";"): one or two natural-language sentences describing THIS panel's moment. NAME each character and bind their pose/action/expression/gaze to them; describe interactions and action-relevant props/clothing; describe framing in plain English (over-the-shoulder from behind X, low angle, close-up, wide shot); for depth/OTS explicitly state who is back-to-camera & blurred in the foreground vs who faces the camera in sharp focus; give characters DISTINCT related poses (e.g. "seated while the other stands over her"). Present tense.

5) SHOT LINE (unlabeled, no ";", directly after the composition sentence): technical camera + light — shot distance (close-up/medium shot/wide shot), depth of field (shallow depth of field, bokeh), lighting quality + color (fluorescent lighting, rim light, cool blue monitor glow). Do not restate the setting or identity.

6) STORY BLOCK: a line exactly "--- STORY ---", then this panel's narration/dialogue for the reader — "Narration: ..." for captions and 'Name: "..."' for each speaker. NOT part of the image prompt; keep it short.

STRUCTURE & FLOW RULES

7) Each panel is immediately preceded by its delimiter line, exactly "=== PANEL {n} ===" (n from 1, incrementing, nothing else on the line).

8) CONTINUATION: if prior panels or a synopsis are provided, write only the NEW panels that come next — never re-output or renumber earlier panels — and keep all established characters, clothes, and world details consistent.

9) PANEL COUNT: the requested count is an UPPER guide, not a minimum. Write up to that many, but if the story reaches its natural conclusion, END there with FEWER panels — never pad, stall, or invent filler.

10) After the LAST panel, output one final block starting with "=== SYNOPSIS ===", then a concise running summary: key characters (with their locked appearance/clothes) plus the plot state so far, so it can seed the next continuation.

11) When the story is COMPLETE (its arc has fully resolved), output one final line, exactly "=== END ===", as the very last line — after the "=== SYNOPSIS ===" block. If the story is NOT finished, do NOT output "=== END ===".

12) Output ONLY the delimiter lines, the panels (image lines + STORY block), the final synopsis block, and (when complete) the trailing "=== END ===" line. No preamble, no commentary, no markdown fences.
"""


def build_messages(
    system_prompt: str,
    brief: str,
    target_panels: int,
    character_bible: str = "",
    previous_panels: str = "",
    synopsis: str = "",
) -> list[dict]:
    """Build the OpenAI-style `messages` list for the chat-completions request.

    `system_prompt` is used verbatim as the `system` role message — this
    function never templates or `.format()`s it. The `user` role message
    folds in the brief, the panel-count guidance (see below), the character
    bible, and (for a continuation call) the prior synopsis / already-written
    panels, so the model sees everything it needs in one place.

    Panel-count guidance: `target_panels <= 0` ("auto") tells the model to
    write as many panels as this part of the story needs, wrapping up if it
    reaches its ending; `target_panels > 0` frames the count as an UPPER cap
    ("up to about N"), never a minimum to pad toward (see
    `DEFAULT_SYSTEM_PROMPT`, which backs this up so it holds even if a
    caller supplies a different/blank `system_prompt`).

    Continuation: when `synopsis` and/or `previous_panels` is non-blank, the
    user message adds a "Story so far" / "Panels already written" section
    (in that order) and an explicit instruction to continue the story
    without repeating or renumbering earlier panels.
    """
    user_parts = ["Write panels for this story/scene brief:", "", str(brief or "").strip()]

    if target_panels and target_panels > 0:
        user_parts.append(
            f"Target: write up to about {target_panels} panels in this batch — fewer if the "
            f"story concludes here; do not pad to reach {target_panels}."
        )
    else:
        user_parts.append(
            "Target: write as many panels as this part of the story needs; if the story "
            "reaches its ending, wrap it up."
        )

    bible = str(character_bible or "").strip()
    if bible:
        user_parts.extend(["", "Character bible (keep these characters visually consistent):", bible])

    synopsis = str(synopsis or "").strip()
    if synopsis:
        user_parts.extend(["", "Story so far (synopsis):", synopsis])

    previous = str(previous_panels or "").strip()
    if previous:
        user_parts.extend(
            ["", "Panels already written (do NOT repeat these — continue from here):", previous]
        )

    if synopsis or previous:
        user_parts.extend(
            [
                "",
                "This is a CONTINUATION: write ONLY the next new panels (never repeat or "
                "renumber the panels above), keep every established character's appearance, "
                "clothes, and the world consistent, and continue the panel numbering from "
                "where it left off.",
            ]
        )

    return [
        {"role": "system", "content": str(system_prompt or "")},
        {"role": "user", "content": "\n".join(user_parts)},
    ]


def build_payload(
    model: str,
    messages: list[dict],
    temperature: float,
    max_tokens: int,
    seed: int = 0,
) -> dict:
    """Build the OpenAI-schema chat-completions request body.

    `seed` is included only when strictly greater than 0 — a seed of 0 (the
    default) omits the field entirely rather than sending a literal `0`,
    since not every OpenAI-compatible backend treats `0` as "no seed".
    """
    payload: dict = {
        "model": model,
        "messages": messages,
        "temperature": temperature,
        "max_tokens": max_tokens,
    }
    if seed and seed > 0:
        payload["seed"] = seed
    return payload


def extract_content(response_json: dict) -> str:
    """Pull `choices[0].message.content` out of a chat-completions response.

    Raises `ValueError` with a clear message if the response is missing any
    expected piece of that shape (malformed/error response body).
    """
    if not isinstance(response_json, dict):
        raise ValueError(f"Expected a JSON object response, got {type(response_json).__name__}")

    choices = response_json.get("choices")
    if not isinstance(choices, list) or not choices:
        raise ValueError(f"Response has no 'choices' list: {response_json!r}")

    first = choices[0]
    if not isinstance(first, dict):
        raise ValueError(f"Response choices[0] is not an object: {first!r}")

    message = first.get("message")
    if not isinstance(message, dict):
        raise ValueError(f"Response choices[0].message is not an object: {message!r}")

    content = message.get("content")
    if not isinstance(content, str):
        raise ValueError(f"Response choices[0].message.content is missing or not a string: {content!r}")

    return content


_SYNOPSIS_MARKER_RE = re.compile(r"^\s*=+\s*SYNOPSIS\s*=+\s*$", re.IGNORECASE | re.MULTILINE)


def split_panels_and_synopsis(content: str) -> tuple[str, str]:
    """Split raw LLM `content` on the FIRST `=== SYNOPSIS ===` marker line.

    The marker is matched as a full line, case-insensitively, tolerant of
    surrounding whitespace and a variable number of `=` characters (e.g.
    `"====SYNOPSIS===="` or `"=== synopsis ==="` both match). Returns
    `(panels_text, synopsis)`, both stripped: everything before the marker
    is `panels_text` (so `PanelBatch` never turns the synopsis into a
    panel), everything after is `synopsis`. If no marker is found, returns
    `(content.strip(), "")` — the whole content is treated as panels text
    and the synopsis is empty.
    """
    content = content or ""
    match = _SYNOPSIS_MARKER_RE.search(content)
    if not match:
        return content.strip(), ""

    panels_text = content[: match.start()].strip()
    synopsis = content[match.end() :].strip()
    return panels_text, synopsis
